/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Composer;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author luizl
 */
public class ViewServidor extends javax.swing.JDialog {

    private boolean servido_wamp = false;

    /**
     * Creates new form NewJDialog
     */
    public ViewServidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(new Color(255, 255, 255));
        initComponents();
        //Como alterar o ícone default do java JFrame Swing?
        URL url = this.getClass().getResource("/Imagens/composer_icone.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        jLabel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPainel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPainel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servidor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/OK.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPainel4.setForeground(new java.awt.Color(238, 112, 82));
        jPainel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPainel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/wamp_server.png"))); // NOI18N
        jPainel4.setText("WAMP SERVER");
        jPainel4.setToolTipText("Permite adicionar e editar atributos de uma tabela ou manualmente");
        jPainel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPainel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPainel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPainel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPainel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPainel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPainel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPainel4MouseEntered(evt);
            }
        });
        jPanel1.add(jPainel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/OK.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPainel5.setForeground(new java.awt.Color(238, 112, 82));
        jPainel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPainel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/xamp.png"))); // NOI18N
        jPainel5.setText("XAMP");
        jPainel5.setToolTipText("Permite adicionar e editar atributos de uma tabela ou manualmente");
        jPainel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPainel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPainel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPainel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPainel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPainel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPainel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPainel5MouseEntered(evt);
            }
        });
        jPanel1.add(jPainel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPainel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPainel4MouseEntered
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        setServido_wamp(true);
        jLabel5.setVisible(true);
    }//GEN-LAST:event_jPainel4MouseEntered

    private void jPainel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPainel5MouseEntered
        setServido_wamp(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(true);
    }//GEN-LAST:event_jPainel5MouseEntered

    private void jPainel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPainel4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jPainel4MouseClicked

    private void jPainel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPainel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jPainel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewServidor dialog = new ViewServidor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jPainel4;
    private javax.swing.JLabel jPainel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the servido_wamp
     */
    public boolean isServido_wamp() {
        return servido_wamp;
    }

    /**
     * @param servido_wamp the servido_wamp to set
     */
    public void setServido_wamp(boolean servido_wamp) {
        this.servido_wamp = servido_wamp;
    }

//get e set
}
